
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERODECIMAL = 52;
  public static final int WHEN = 12;
  public static final int PUBLICO = 4;
  public static final int PARENTESIS_CIERRE = 56;
  public static final int MODULO_Y_ASIGNACION = 49;
  public static final int IMPRIMIR = 23;
  public static final int FUNCION = 8;
  public static final int RESTA = 38;
  public static final int DOS_PUNTOS = 61;
  public static final int TIPO_STRING = 16;
  public static final int FOR = 13;
  public static final int IDENTIFICADOR = 50;
  public static final int SUMA_Y_ASIGNACION = 45;
  public static final int PRIVADO = 5;
  public static final int AND = 34;
  public static final int CORCHETE_CIERRE = 58;
  public static final int TIPO_BOOLEAN = 21;
  public static final int CARACTER = 54;
  public static final int MULTIPLICACION_Y_ASIGNACION = 47;
  public static final int OR = 35;
  public static final int DIVISION_Y_ASIGNACION = 48;
  public static final int FIN_PROGRAMA = 3;
  public static final int SUMA = 37;
  public static final int IF = 10;
  public static final int PUNTO_COMA = 62;
  public static final int RETORNO = 9;
  public static final int EOF = 0;
  public static final int ESTATICO = 7;
  public static final int CORCHETE_APERTURA = 57;
  public static final int TRUE = 25;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int COMA = 65;
  public static final int CADENA = 53;
  public static final int RESTA_Y_ASIGNACION = 46;
  public static final int TIPO_DOUBLE = 20;
  public static final int TIPO_CHAR = 17;
  public static final int COMENTARIO = 63;
  public static final int MODULO = 41;
  public static final int NEGACION = 36;
  public static final int MAYOR_QUE = 28;
  public static final int OPERADOR_INCREMENTO = 43;
  public static final int TIPO_INT = 18;
  public static final int ERROR = 66;
  public static final int IMPRIMIR_CON_SALTO = 24;
  public static final int COMENTARIO_MULTILINEA = 64;
  public static final int INICIO_PROGRAMA = 2;
  public static final int ENTRADA = 22;
  public static final int DIFERENTE_DE = 31;
  public static final int ELSE = 11;
  public static final int LLAVE_APERTURA = 59;
  public static final int OPERADOR_DECREMENTO = 44;
  public static final int IGUAL_A = 30;
  public static final int WHILE = 14;
  public static final int IFX = 67;
  public static final int ASIGNACION_VALOR = 42;
  public static final int MAYOR_IGUAL = 32;
  public static final int TIPO_FLOAT = 19;
  public static final int LLAVE_CIERRE = 60;
  public static final int PROTEGIDO = 6;
  public static final int PARENTESIS_APERTURA = 55;
  public static final int MENOR_QUE = 29;
  public static final int MENOR_IGUAL = 33;
  public static final int FALSE = 26;
  public static final int DIVISION = 40;
  public static final int NUMERO_ENTERO = 51;
  public static final int DO = 15;
  public static final int MULTIPLICACION = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO_PROGRAMA",
  "FIN_PROGRAMA",
  "PUBLICO",
  "PRIVADO",
  "PROTEGIDO",
  "ESTATICO",
  "FUNCION",
  "RETORNO",
  "IF",
  "ELSE",
  "WHEN",
  "FOR",
  "WHILE",
  "DO",
  "TIPO_STRING",
  "TIPO_CHAR",
  "TIPO_INT",
  "TIPO_FLOAT",
  "TIPO_DOUBLE",
  "TIPO_BOOLEAN",
  "ENTRADA",
  "IMPRIMIR",
  "IMPRIMIR_CON_SALTO",
  "TRUE",
  "FALSE",
  "NEW",
  "MAYOR_QUE",
  "MENOR_QUE",
  "IGUAL_A",
  "DIFERENTE_DE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "AND",
  "OR",
  "NEGACION",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "ASIGNACION_VALOR",
  "OPERADOR_INCREMENTO",
  "OPERADOR_DECREMENTO",
  "SUMA_Y_ASIGNACION",
  "RESTA_Y_ASIGNACION",
  "MULTIPLICACION_Y_ASIGNACION",
  "DIVISION_Y_ASIGNACION",
  "MODULO_Y_ASIGNACION",
  "IDENTIFICADOR",
  "NUMERO_ENTERO",
  "NUMERODECIMAL",
  "CADENA",
  "CARACTER",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "CORCHETE_APERTURA",
  "CORCHETE_CIERRE",
  "LLAVE_APERTURA",
  "LLAVE_CIERRE",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "COMENTARIO",
  "COMENTARIO_MULTILINEA",
  "COMA",
  "ERROR",
  "IFX"
  };
}

